kind: pipeline
type: docker
name: default

steps:
- name: build
  image: plugins/hugo
  settings:
    extended: true
    hugo_version: "0.74.3"
    config: config.yaml

trigger:
  event:
  - push
  - pull_request
